using Content.Client.Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Prototypes;

namespace Content.Client.Photography;

[GenerateTypedNameReferences]
public sealed partial class PhotoWindow : DefaultWindow {

    public PhotoWindow(IEye? eye, Vector2i size)
    {
        RobustXamlLoader.Load(this);

        PhotoView.Eye = eye;
        PhotoView.ViewportSize = size;

        OpenCentered();
    }
}
