using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.Salvage.UI;

/// <summary>
/// Generic window for offering multiple selections with a timer.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OfferingWindow : FancyWindow,
    IComputerWindow<EmergencyConsoleBoundUserInterfaceState>
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public bool Claimed;
    public TimeSpan NextOffer;

    public TimeSpan? ClaimTime;

    /// <summary>
    /// Time between NextOffers
    /// </summary>
    public TimeSpan Cooldown;

    /// <summary>
    /// Time between Progressions
    /// </summary>
    public TimeSpan ProgressionCooldown;

    public event Action<string>? OnSalvageEnd;

    public OfferingWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        EndButton.OnPressed += _ => OnSalvageEnd?.Invoke("");
    }

    public void AddOption(OfferingWindowOption option)
    {
        Container.AddChild(option);
    }

    public void AddPlaceholderOption(Placeholder option)
    {
        Container.AddChild(option);
    }

    public void ClearOptions()
    {
        Container.RemoveAllChildren();
    }

    public void EnableClaimScreen(bool enable)
    {
        OfferingContainer.Visible = !enable;
        WreckContainer.Visible = enable;
    }

    public void UpdateTileProgression(float percentage)
    {
        WreckCompletionBar.Value = percentage;
        WreckCompletionText.Text = percentage.ToString("P2");
    }

    public void UpdateShredderEfficiency(float percentage)
    {
        if (percentage > 0.9f)
            EfficiencyText.Text = "[color=#69ff63]" + percentage.ToString("P0") + "[/color]";
        else if (percentage > 0.4f)
            EfficiencyText.Text = "[color=#efff63]" + percentage.ToString("P0") + "[/color]";
        else
            EfficiencyText.Text = "[color=#ff6363]" + percentage.ToString("P0") + "[/color]";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (Claimed)
        {
            NextOfferBar.Value = 1f;
            NextOfferText.Text = "00:00";
        }
        else
        {
            var remaining = NextOffer - _timing.CurTime;

            if (remaining < TimeSpan.Zero)
            {
                NextOfferBar.Value = 1f;
                NextOfferText.Text = "00:00";
            }
            else
            {
                NextOfferBar.Value = 1f - (float) (remaining / Cooldown);
                NextOfferText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
            }
        }

        if (ClaimTime != null)
        {
            var claimTime = _timing.CurTime.Subtract(ClaimTime.Value);
            ClaimTimerText.Text = claimTime.ToString("mm\\:ss");
        }
    }
}
